---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-conf
  labels:
    app: opentelemetry
    component: otel-collector-conf
data:
  otel-collector-config: |
    extensions:
      health_check:
      http_forwarder:
        egress:
          endpoint: "https://api.eu0.signalfx.com"
      zpages:
    receivers:
      sapm:
      signalfx:
      # This section is used to collect OpenTelemetry metrics
      # Even if just a SignalFx µAPM customer, these metrics are included
      otlp:
       protocols:
        grpc:
        http:
      prometheus:
        config:
          scrape_configs:
            - job_name: 'otel-collector'
              scrape_interval: 10s
              static_configs:
                - targets: ['localhost:8888']
                  # If you want to use the environment filter
                  # In the SignalFx dashboard
                  #labels:
                    #environment: demo
              metric_relabel_configs:
                - source_labels: [ __name__ ]
                  regex: '.*grpc_io.*'
                  action: drop
      # Enable Zipkin to support Istio Mixer Adapter
      # https://github.com/signalfx/signalfx-istio-adapter
      zipkin:
    processors:
      batch:
      # Optional: If you have a different environment tag name
      # If this option is enabled it must be added to the pipeline section below
      #attributes/copyfromexistingkey:
        #actions:
        #- key: environment
          #from_attribute: YOUR_EXISTING_TAG_NAMEE
          #action: upsert
      # Optional: If you want to add an environment tag
      # If this option is enabled it must be added to the pipeline section below
      attributes/newenvironment:
        actions:
        - key: environment
          value: "DEV"
          action: insert
      # Enabling the memory_limiter is strongly recommended for every pipeline.
      # Configuration is based on the amount of memory allocated to the collector.
      # The configuration below assumes 2GB of memory. In general, the ballast
      # should be set to 1/3 of the collector's memory, the limit should be 90% of
      # the collector's memory up to 2GB, and the spike should be 25% of the
      # collector's memory up to 2GB. In addition, the "--mem-ballast-size-mib" CLI
      # flag must be set to the same value as the "ballast_size_mib". For more
      # information, see
      # https://github.com/open-telemetry/opentelemetry-collector/blob/master/processor/memorylimiter/README.md
      memory_limiter:
        ballast_size_mib: 683
        check_interval: 2s
        limit_mib: 1800
        spike_limit_mib: 500
    exporters:
      # Traces
      sapm:
        access_token: ""
        endpoint: "https://ingest.eu0.signalfx.com/v2/trace"
      # Metrics
      signalfx:
        access_token: ""
        realm: "eu0"
    service:
      extensions: [health_check, http_forwarder, zpages]
      pipelines:
        traces:
          receivers: [sapm, zipkin, otlp]
          processors: [memory_limiter, batch, attributes/newenvironment]
          exporters: [sapm]
        metrics:
          receivers: [signalfx, prometheus, otlp]
          processors: [memory_limiter, batch]
          exporters: [signalfx]
        logs:
          receivers: [signalfx]
          processors: [memory_limiter, batch]
          exporters: [signalfx]
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  ports:
  - name: sapm # Default endpoint for SignalFx APM receiver.
    port: 7276
  - name: zipkin # Default endpoint for Zipkin trace receiver.
    port: 9411
  - name: signalfx # Default endpoint for SignalFx metrics receiver.
    port: 9943
  - name: metrics # Default endpoint for the Collector metrics.
    port: 8888
  - name: otlp
    port: 55680
  selector:
    component: otel-collector

---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector-external
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  type: LoadBalancer
  selector:
    component: otel-collector
  ports:
  - protocol: TCP
    port: 8888
    name: metrics # Default endpoint for the Collector metrics.
    targetPort: 8888
  - protocol: TCP
    port: 55680
    name: otlp
    targetPort: 55680
  - protocol: TCP
    port: 4317
    name: otlpd
    targetPort: 4317
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  selector:
    matchLabels:
      app: opentelemetry
      component: otel-collector
  minReadySeconds: 5
  progressDeadlineSeconds: 120
  replicas: 1 #TODO - adjust this to your own requirements
  template:
    metadata:
      labels:
        app: opentelemetry
        component: otel-collector
    spec:
      containers:
      - command:
          - "/otelcontribcol"
          - "--config=/conf/otel-collector-config.yaml"
#           Memory Ballast size should be max 1/3 to 1/2 of memory.
          - "--mem-ballast-size-mib=683"
        image: otel/opentelemetry-collector-contrib:0.12.0
        name: otel-collector
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 400Mi
        ports:
        - containerPort: 55679 # Default endpoint for ZPages.
        - containerPort: 55680 # Default endpoint for OpenTelemetry receiver.
        - containerPort: 6060  # Default endpoint for HTTP Forwarder extension.
        - containerPort: 7276  # Default endpoint for SignalFx APM receiver.
        - containerPort: 8888  # Default endpoint for querying metrics.
        - containerPort: 9411  # Default endpoint for Zipkin trace receiver.
        - containerPort: 9943  # Default endpoint for SignalFx metrics receiver.
        - containerPort: 4317   # otlp receiver
        volumeMounts:
        - name: otel-collector-config-vol
          mountPath: /conf
#        - name: otel-collector-secrets
#          mountPath: /secrets
        livenessProbe:
          httpGet:
            path: /
            port: 13133 # Health Check extension default port.
        readinessProbe:
          httpGet:
            path: /
            port: 13133 # Health Check extension default port.
      volumes:
        - configMap:
            name: otel-collector-conf
            items:
              - key: otel-collector-config
                path: otel-collector-config.yaml
          name: otel-collector-config-vol
#        - secret:
#            name: otel-collector-secrets
#            items:
#              - key: cert.pem
#                path: cert.pem
#              - key: key.pem
#                path: key.pem
